=== gradleutil/conf/src/test/resources/json/MinecraftConfig.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/MinecraftConfig",
  "definitions": {
    "MinecraftConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string",
          "title": "Schema",
          "description": "Pointer to the schema against which this document should be validated."
        },
        "name": {
          "type": "string"
        },
        "minecraftDataDir": {
          "type": "string",
          "default": "\\\\AppData\\\\Roaming\\\\.minecraft"
        },
        "databasePath": {
          "type": "string",
          "default": "./data.db"
        },
        "minecrafts": {
          "type": "array",
          "title": "Minecrafts",
          "items": {
            "$ref": "#/definitions/Minecraft"
          }
        },
        "git": {
          "$ref": "#/definitions/Git"
        },
        "modRepo": {
          "type": "array",
          "title": "ModRepo",
          "items": {
            "$ref": "#/definitions/Repository"
          }
        },
        "publishing": {
          "type": "array",
          "title": "Publishing",
          "items": {
            "$ref": "#/definitions/Repository"
          }
        }
      },
      "required": [
        "name"
      ],
      "title": "MinecraftConfig"
    },
    "Minecraft": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "vanilla",
            "forge",
            "spigot",
            "paper"
          ]
        },
        "version": {
          "enum": [
            "1.19.1",
            "1.19",
            "1.19-Snapshot",
            "1.18.2",
            "1.18.1",
            "1.18",
            "1.18-Snapshot",
            "1.17.1",
            "1.17",
            "1.17-Snapshot",
            "1.16.5",
            "1.16.4",
            "1.16.3",
            "1.16.2",
            "1.16.1",
            "1.16",
            "1.16-Snapshot",
            "1.15.2",
            "1.15.1",
            "1.15",
            "1.15-Snapshot",
            "1.14.4",
            "1.14.3",
            "1.14.2",
            "1.14.1",
            "1.14",
            "1.14-Snapshot",
            "1.13.2",
            "1.13.1",
            "1.13",
            "1.13-Snapshot",
            "1.12.2",
            "1.12.1",
            "1.12",
            "1.12-Snapshot",
            "1.11.2",
            "1.11.1",
            "1.11",
            "1.11-Snapshot",
            "1.10.2",
            "1.10.1",
            "1.10-Snapshot",
            "1.10",
            "1.9.4",
            "1.9.3",
            "1.9.2",
            "1.9.1",
            "1.9",
            "1.9-Snapshot",
            "1.8.9",
            "1.8.8",
            "1.8.7",
            "1.8.6",
            "1.8.5",
            "1.8.4",
            "1.8.3",
            "1.8.2",
            "1.8.1",
            "Beta 1.8.1",
            "1.8",
            "1.8-Snapshot",
            "1.7.10",
            "1.7.9",
            "1.7.8",
            "1.7.7",
            "1.7.6",
            "1.7.5",
            "1.7.4",
            "1.7.3",
            "Beta 1.7.3",
            "1.7.2",
            "Beta 1.7",
            "Beta 1.6.6",
            "1.6.4",
            "1.6.2",
            "1.6.1",
            "1.5.2",
            "1.5.1",
            "1.5.0",
            "1.4.7",
            "1.4.6",
            "1.4.5",
            "1.4.4",
            "1.4.2",
            "1.3.2",
            "1.3.1",
            "1.2.5",
            "1.2.4",
            "1.2.3",
            "1.2.2",
            "1.2.1",
            "1.1",
            "1.0.0",
            "1.0"
          ]
        },
        "mods": {
          "type": "array",
          "title": "Mods",
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/Mod"
          }
        }
      },
      "required": ["version", "type" ]
    },
    "Mod": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "authors": {
          "type": "array",
          "title": "Authors",
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/Author"
          }
        },
        "artifacts": {
          "type": "array",
          "title": "Artifacts",
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/ModArtifact"
          }
        }
      },
      "required": [
        "name"
      ],
      "title": "Mod"
    },
    "Author": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {"type": "string"},
        "id": {"type": "number"},
        "url": {"type": "string"}
      }
    },
    "ModArtifact": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "downloadUrl": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "fileId": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        },
        "minecraft": {
          "$ref": "#/definitions/Minecraft"
        },
        "dependencies": {
          "type": "array",
          "uniqueItems": true,
          "title": "dependencies",
          "items": {
            "$ref": "#/definitions/ModArtifact"
          }
        },
        "mavenDependency": {
          "type": "string"
        }
      },
      "required": [
        "version",
        "minecraft"
      ],
      "title": "Mod Artifact"
    },
    "Repository": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "file",
            "maven",
            "scp",
            "git"
          ]
        },
        "url": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "port": {
          "type": "integer"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials"
        }
      },
      "if": {
        "properties": { "type": { "const": "scp" } }
      },
      "then": {
        "required": [
          "host","credentials","path"
        ]
      },
      "required": [
        "type"
      ],
      "title": "Repository"
    },
    "Credentials": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "url": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "identityFile": {
          "type": "string"
        },
        "passphrase": {
          "type": "string"
        }
      },
      "required": [
      ],
      "title": "Credentials"
    },

    "Git": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "dir": {
          "type": "string",
          "default": "'~/minecraft'"
        },
        "repoUri": {
          "type": "string",
          "default": "'https://github.com/minecraft'"
        }
      },
      "required": [
        "dir",
        "repoUri"
      ],
      "title": "Git"
    }
  }
}

=== gradleutil/conf/src/test/resources/json/MinecraftConfig.json
{
  "$schema": "MinecraftConfig.schema.json",
  "name": "my nice minecraft config",
  "publishing": [
    {
      "type": "file",
      "path": "/tmp/mcuni"
    }
  ],
  "git": {
    "dir": "./git",
    "repoUri": "ut"
  },
  "minecrafts": [
    {
      "version": "1.10",
      "type": "vanilla",
      "mods": [
        {
          "name": "my awesome mod",
          "slug": "atmosphere",
          "id": "nothanks",
          "description": "this is a  lot of text",
          "artifacts": [
            {
              "name": "name",
              "version": "234",
              "fileId": "234",
              "downloadUrl": "",
              "minecraft": {
                "version": "1.15.2",
                "type": "paper"
              }
            }
          ]
        }
      ]
    }
  ]
}
